[project]
name = "llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mistralai>=1.5.0",
    "openai>=1.60.2",
    "pyperclip>=1.9.0",
    "rich>=13.9.4",
    "together>=1.3.14",
    "trafilatura>=2.0.0",
]
